### ISSUE TITLE
Colliding of parallel labels

### ISSUE THREAD

**Issue by W14A** [DotSpatial/DotSpatial#969] opened 2017-04-06 10:27 UTC
DotSpatial version:  1.8,1.9,2.0

If u want some Labels to allign to a LineLayer below(Streets should be the common example) the Collsion detection only works for like 80% of the Labels. Well, it removes a lot of the colliding Labels, but not all of them, so its a completely unusable feature. While i tested through the options the Collision detection only really works if the Labels are Horizontal, and u just cant Label streets horizontal.
So, since this problem seems to be present since v1.8 and is still in 2.0, is there any hope for a fix or is there a way to workaround ? Would be kinda dissapointing if i have to switch off from DotSpatial cause i really need clean street names.

![grafik](https://cloud.githubusercontent.com/assets/14258794/24749157/5159a436-1ac2-11e7-9dce-fdc8f84834f3.png)

**Comment by jany-tenaj** [comment] 2017-04-06 11:01
This is a duplicate of #740.

Maybe as a workaround you could set the dynamic visibility scale of the labels to a scale that is small enough that the labels don't collide there.

**Comment by W14A** [comment] 2017-04-06 11:06
I know that it was a duplicate, i just reopened it cause there was never an answer on the other issue.
And thats not a workaround at all, cause even on close scale they gonna collide all the way.
![grafik](https://cloud.githubusercontent.com/assets/14258794/24751372/9e79082c-1ac9-11e7-9766-ba10fd1677f6.png)

**Comment by mogikanin** [comment] 2017-04-06 11:26
@W14A maybe you want to investigate and propose fix for this issue, if it so critical for you? DS is non-commercial product, so any help are appreciated.

**Comment by mmousa4** [comment] 2017-11-08 18:13
Hi,
I have the same problem. I've searched a lot, but came up with no solution. 
If you found any solution , would you please share it. 

Thanks

**Comment by W14A** [comment] 2017-11-09 05:09
Yeah sry there is no Solution. I had no time in my project to fix some shitty errors in the dll's. I switched to mapwingis.ocx and it works wonderful.

**Comment by mmousa4** [comment] 2017-11-09 17:42
Thanks, It is appreciated

**Closed** 2023-02-02 06:39 UTC
Labels: duplicate
