### ISSUE TITLE
Online Basemap shown incorrectly after #1341

### ISSUE THREAD

**Issue by jany-tenaj** [DotSpatial/DotSpatial#1351] opened 2020-07-01 09:45 UTC
### Steps to reproduce

1. Open the dspx from the [error.zip](https://github.com/DotSpatial/DotSpatial/files/4856925/error.zip).
2. Zoom to max extent.

DotSpatial version: current master

### Expected behaviour

Basemap should look like this:
![correctmap](https://user-images.githubusercontent.com/13728699/86228166-58ee8c00-bb8e-11ea-94ac-57a3c6717b57.png)

### Actual behaviour

Basemap looks like this:
![errormap](https://user-images.githubusercontent.com/13728699/86228162-568c3200-bb8e-11ea-9aea-d8b760bd3cad.png)

@VectorZita Could you please check this out? Otherwise I'd revert #1341.

**Comment by VectorZita** [comment] 2020-07-04 18:53
Seems strange... I will try to take a look as soon as possible, and let you know.

**Comment by Neverlyn** [comment] 2020-09-06 12:33
I just updated to the latest version and am having the same issue, needed to revert back to b1e34ef.

**Comment by Scott2142** [comment] 2020-09-06 13:47
Same here. I update recently and this is causing me some headaches. Will look into older versions for now.

**Comment by AndyMonteiro** [comment] 2020-09-19 14:59
Seems to be the code for fix #1326 Potential bug in EnvelopeExt (and ExtentExt) class Reproportion(...) method checked in on May 8th, 2020.

Changes to ExtentExt.cs 

old            return new Extent(self.X + dx, self.Y + dy **- h**, self.X + dx + w, self.Y + dy);
new           return new Extent(self.X + dx, self.Y + dy, self.X + dx + w, self.Y + dy **+ h**);

and EnvelopeExt.cs

old            return new Envelope(self.MinX + dx, self.MinX + dx + w, self.MinY + dy **- h**, self.MinY + dy);
new           return new Envelope(self.MinX + dx, self.MinX + dx + w, self.MinY + dy, self.MinY + dy **+ h**);

Reverting those two lines makes things work for me.

**Comment by jany-tenaj** [comment] 2020-09-21 07:08
@AndyMonteiro I know that that is the cause for this error. But it fixed other things. So the question would be which lines inside WebMap have to be fixed so it will work with the changed code from #1326.

**Comment by VectorZita** [comment] 2020-09-30 18:26
@All I apologize for not having looked into this so far, I was really too short of time. I will do my best to check this out as soon as possible.

**Comment by VectorZita** [comment] 2020-10-03 10:47
@jany-tenaj OK, I got this!

The problem is in the **ExtentExt.Reproportion()** method. In #1326, I have made a small analysis for the case of the **EnvelopeExt** class and assumed the fix would be similar for the **ExtentExt** class, so I didn't delve into that one back then.

However, while in the case of **Envelope**, there is a clear and concise use of properties such as _MinX_, _MaxX_, _MinY_ and _MaxY_, the **Extent** class also contains _X_ and _Y_ properties, which may be a bit unexpected in terms of what they do. Taking a look into the Extent class, it appears that _X_ actually returns _MinX_ but _Y_ actually returns **MaxY**. In #1341, the fix for the **ExtentExt** class replaces line:

`return new Extent(self.X + dx, self.Y + dy - h, self.X + dx + w, self.Y + dy);`

with

`return new Extent(self.X + dx, self.Y + dy, self.X + dx + w, self.Y + dy + h);`

In #1326, the proposed return value for EnvelopeExt was:

`return new Envelope(self.MinX + dx, self.MinX + dx + w, self.MinY + dy, self.MinY + dy + h);`

The first **catch** here is that Envelope and Extent don't actually have identical constructors... In short, it's Envelope(xMin, xMax, yMin, yMax) but it's Extent(xMin, yMin, xMax, yMax), so the order would have to change to properly accommodate the fix (which it did, of course). And then, there is also the _X_ and _Y_ properties, which **don't actually correspond to _MinX_ and _MinY_**. If the correspondence is fixed (i.e. accounting for constructor parameter order **and** using _MinX_ and _MinY_ instead of _X_ and _Y_), the final line (which also appears to fix the problem) reads:

(**1**): `return new Extent(self.MinX + dx, self.MinY + dy, self.MinX + dx + w, self.MinY + dy + h);`

However, since there was obviously no problem with the drawing of the Base Map before issue #1326, it follows that this result must be equivalent to the original return value (before fix #1341):

(**2**): `return new Extent(self.X + dx, self.Y + dy - h, self.X + dx + w, self.Y + dy);`

Now that I have revisited #1326 for **ExtentExt** as well (as #1326 primarily aimed at EnvelopeExt), the reason why this is correct is more obvious; _Y_ is not _MinY_, it is _MaxY_ and that is why the original version actually worked fine. Also, for **Envelope**, there is no X or Y but only MinX and MinY, so it may be the case that the **EnvelopeExt** was an attempt to extrapolate from the **ExtentExt** (it performs the same logic after all), which seems to have missed the fact that **Extent.Y** actually refers to **Extent.MaxY**, thus leading to incorrect Raster Layer display when rendering **PyramidImage**-based layers (e.g. parts of #512 and #901).

There is still a small displacement between my interpretation and the originally produced Extent above (i.e. between **1** and **2**), which does not seem to have any visual impact on the result. I will think a bit more about it and post if I have anything new. For the time being, using either (**1**) or (**2**) above as the ending line of **ExtentExt.Reproportion(...)** should fix the problem.

**Comment by AndyMonteiro** [comment] 2020-10-03 18:28
Nice! I hadn't yet had time to look at this myself, so appreciate you guys figuring it out!

**Comment by jany-tenaj** [comment] 2020-10-05 07:10
@VectorZita I think that we have Extent and Envelope comes from the fact that everything exists twice. Once from NetTopologySuite (e.g. Envelope, Geometry) and once implemented in DotSpatial (Extent, Shape). So calculations exist twice also and we've got twice as many places where we have to fix errors. ;)

**Comment by Neverlyn** [comment] 2020-11-07 14:07
Has this issue been figured out? If yes, will the fix be committed soon?

**Comment by gfernan** [comment] 2020-12-14 16:40
> ### Steps to reproduce
> 1. Open the dspx from the [error.zip](https://github.com/DotSpatial/DotSpatial/files/4856925/error.zip).
> 2. Zoom to max extent.
> 
> DotSpatial version: current master
> 
> ### Expected behaviour
> Basemap should look like this:
> ![correctmap](https://user-images.githubusercontent.com/13728699/86228166-58ee8c00-bb8e-11ea-94ac-57a3c6717b57.png)
> 
> ### Actual behaviour
> Basemap looks like this:
> ![errormap](https://user-images.githubusercontent.com/13728699/86228162-568c3200-bb8e-11ea-9aea-d8b760bd3cad.png)
> 
> @VectorZita Could you please check this out? Otherwise I'd revert #1341.

Is this issue on webmap been fixed in the latest master code?

**Comment by gfernan** [comment] 2020-12-14 16:40
Is this issue on webmap  been fixed in the latest master code? thanks.

**Comment by sindizzy** [comment] 2020-12-20 02:03
I ran a quick test on the project that was provided:

This is what results in the routine that worked
-1: xmin=1489515.63568846 ymin=6892710.87985726 xmax=1492458.04389689 ymax=6894850.34216375

This is what results from the current routine plus the two fixes proposed above
0: xmin=1489515.63568846 ymin=6894850.34216375 xmax=1492458.04389689 ymax=6896989.80447023
1: xmin=1489515.63568846 ymin=6892752.32222639 xmax=1492458.04389689 ymax=6894891.78453288
2: xmin=1489515.63568846 ymin=6892710.87985726 xmax=1492458.04389689 ymax=6894850.34216375

From inspection we see that that proposal #2 gives you the same extents as the  original routine that worked. I'll write that pull request and credit @VectorZita.  Also ExtentExt.Reproportion seems to only have one call reference from   DotSpatial.Controls.MapImageLayer.DrawWindows.

**Closed** 2021-01-04 10:50 UTC
