### ISSUE TITLE
Rounding error in version 1.9 but not in 2.0 when converting to WKT

### ISSUE THREAD

**Issue by pedwik** [DotSpatial/DotSpatial#937] opened 2017-02-10 21:19 UTC
In version 1.9, saving a feature to a WKT gives a rounding error. Example:

```
var c = new Coordinate(481408.90381056763, 6624970.0);
IFeature f = new Feature(FeatureType.Point, new List<Coordinate>() {c});
var wkt = f.BasicGeometry.ToString();
```

results in truncatation of the 10th decimal:
`wkt = "POINT (481408.9038105680000000 6624970.0000000000000000)"
`

The current trunk (upcoming 2.0) does not result in the same problem:
`wkt = "POINT (481408.90381056763 6624970)"
`

Is there a way to set the precision in 1.9?

**Comment by jany-tenaj** [comment] 2017-02-11 08:55
I think the precision gets set with the help of the PrecisionModel that is used inside the GeometryFactory that is used to create your Geometry.

As far as I could tell without debuging the code there doesn't seem to be a difference. So your difference might comes from some code fixes that were added after the old NTS version that was used for DotSpatial.Topology.

**Comment by pedwik** [comment] 2017-02-11 11:14
I am not clear what you mean that there doesn't seem to be a difference? I get the rounding error when running nuget version 1.9.

**Comment by jany-tenaj** [comment] 2017-02-11 12:02
The code I had a look at didn't seem to be different for 1.9 and 2.0. That's the reason I think changing the precisision might not result in what you want, because the error could be somewhere else.

**Comment by mogikanin** [comment] 2017-04-02 07:28
Since issue is not reproduced in 2.0, then we can close it, is it?

**Comment by pedwik** [comment] 2017-04-02 10:23
Yes, we can close it, but I am away from office and a PC.

Mvh Peder

**Closed** 2017-04-02 10:33 UTC
Labels: question
